--
-- Mascotify Migration: Control de Inventario por Marcas
-- Fecha: 2026-05-04
--

-- 1. Crear tabla de control de marcas
CREATE TABLE IF NOT EXISTS public.marcas_control (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL UNIQUE,
  dias_rango INT NOT NULL DEFAULT 30,
  ultimo_conteo TIMESTAMPTZ,
  inventariar BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Índices
CREATE INDEX IF NOT EXISTS idx_marcas_control_nombre ON public.marcas_control(nombre);
CREATE INDEX IF NOT EXISTS idx_marcas_control_inventariar ON public.marcas_control(inventariar);

-- 3. Trigger para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_marcas_control_updated_at ON public.marcas_control;
CREATE TRIGGER update_marcas_control_updated_at
  BEFORE UPDATE ON public.marcas_control
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- 4. Seed de marcas con frecuencias de conteo
-- Marcas con frecuencia vacía tienen inventariar = false (lista negra)
INSERT INTO public.marcas_control (nombre, dias_rango, inventariar) VALUES
  ('Livelong', 30, true),
  ('Gran Plus', 30, true),
  ('Advance', 30, false),
  ('Progato', 30, false),
  ('Zoetis - Pet Cal', 20, true),
  ('Zoetis - Pet Tabs Plus', 15, true),
  ('Zoetis - Revolution', 20, true),
  ('Zoetis - Simparica', 20, true),
  ('Bayer - Advantage', 30, false),
  ('Bayer - Advantix', 30, false),
  ('Bayer - Equilibrium', 30, false),
  ('Nexgard', 20, true),
  ('Royal Pet', 30, false),
  ('Origens', 30, true),
  ('Ecuphar - Dermocanis', 30, false),
  ('Ecuphar - Orozyme', 30, false),
  ('Frontline', 20, true),
  ('Zeedog', 60, true),
  ('Zeecat', 60, true),
  ('Broadline', 30, false),
  ('Petkin', 30, false),
  ('Genérico', 30, false),
  ('Kumar Steels', 30, false),
  ('Zoetis - ViSorbits', 30, false),
  ('Zoorganica', 30, false),
  ('Collar', 60, true),
  ('Labyes - Feline', 20, true),
  ('Labyes - Protech', 30, true),
  ('Zoetis - Apoquel', 20, true),
  ('Pet-AG', 20, true),
  ('Manna Pro - SS', 30, true),
  ('Manna Pro - VB', 30, true),
  ('Hartz', 30, true),
  ('Omega Paw', 30, true),
  ('WB Cat Litter', 30, true),
  ('Cat It', 30, true),
  ('Dog It', 30, true),
  ('Bayer - Seresto', 30, false),
  ('Cute Cat', 45, true),
  ('KlinKat', 45, true),
  ('Ok Pet', 30, false),
  ('Garfield', 60, true),
  ('LabEca', 20, true),
  ('Hills', 30, true),
  ('Pets Club', 30, false),
  ('VetlineX', 30, false),
  ('Vetnil', 30, true),
  ('Equilibrio', 30, true),
  ('Canbo', 30, true),
  ('Drag-Pharma', 30, true),
  ('Manna Pro - BoB', 60, true),
  ('Waudog', 60, true),
  ('Dingo', 30, true),
  ('Churu', 30, true),
  ('Natures Miracle', 45, true),
  ('Acce Can', 30, true),
  ('Agrovet-CaniTabs', 30, true),
  ('Brit Premium', 30, true),
  ('Bravery', 30, true),
  ('Trixie', 30, false),
  ('Furminator', 30, true),
  ('Bayer - Baytril', 30, false),
  ('Bayer - Advocate', 30, false),
  ('Bayer - Drontal', 30, false),
  ('Good Boy', 30, false),
  ('Comandina', 30, true),
  ('Only-Pet', 30, false),
  ('MSD - Bravecto', 20, true),
  ('MSD - Endal', 45, true),
  ('Vetoquinol', 20, true),
  ('Labyes', 20, true),
  ('Proplan', 30, true),
  ('Ricocat', 30, true),
  ('Ricocan', 30, true),
  ('Coplasti', 30, false),
  ('Intersand', 60, true),
  ('Lickimat', 60, true),
  ('Labyes - Canis', 20, true),
  ('Instinct', 30, false),
  ('Ricocrack', 30, true),
  ('Cats Best', 45, true),
  ('Applaws', 30, true),
  ('Beaphar', 20, true),
  ('Canvit', 30, true),
  ('Brit Care', 30, true),
  ('Ferplast', 45, true),
  ('Monge', 30, true),
  ('Taste of the Wild', 30, true),
  ('Biogance', 45, true),
  ('Carnilove', 30, true),
  ('Gooeez', 60, true),
  ('Asobu', 30, false),
  ('Baul de Coco', 60, true),
  ('Naturo', 30, false),
  ('Agrovet-Atrevia', 20, true),
  ('Max & Molly', 60, true),
  ('Mervue', 30, false),
  ('Yamis', 30, true),
  ('Rex', 30, true),
  ('Nutram', 30, true),
  ('Amity', 30, true),
  ('Pedigree', 30, false),
  ('Whiskas', 30, false),
  ('Biomont - Proteggo', 20, true),
  ('Biomont - Oprurix', 20, true),
  ('Virbac', 20, true),
  ('Triton', 30, false),
  ('Veterline', 30, false),
  ('Bayer - Credelio', 30, false),
  ('Ultima', 30, false),
  ('WeeWee', 60, true),
  ('Belcando', 30, true),
  ('Leonardo', 30, true),
  ('Seven Lives', 30, false),
  ('Kruuse', 30, true),
  ('Kompa', 30, false),
  ('Brit Vet Diet', 30, true),
  ('Biomont', 20, true),
  ('Biomont - Rivolta', 20, true),
  ('Biomont - Vantaggio', 20, true),
  ('Darford', 30, true),
  ('Sentry', 20, true),
  ('Savic', 60, true),
  ('Two Brothers', 45, true),
  ('Gigwi', 45, true),
  ('Cremi', 30, true),
  ('Litter Genie', 60, true),
  ('Skipdawg', 45, true),
  ('Par Pets', 30, true),
  ('Arm & Hammer', 45, true),
  ('Mio Cane', 30, false),
  ('Mio Gatto', 30, false),
  ('New Born', 30, false),
  ('Zeus', 30, true),
  ('Lopets', 30, true),
  ('Mimma', 30, true),
  ('Barker', 30, true),
  ('Natural Home', 30, false),
  ('Guau & Fun', 30, true),
  ('Sonqo', 30, true),
  ('Snout', 30, false),
  ('My Family', 60, true),
  ('Cat Fest', 30, true),
  ('Dog Fest', 30, true),
  ('Guabi Natural', 30, true),
  ('Amazonia', 45, true),
  ('Holland Animal Care', 60, true),
  ('Mishi Sand', 30, false),
  ('Tetra', 30, true),
  ('Agrovet-Suralan', 30, true),
  ('Zoovet', 30, true),
  ('Dolfos Pets', 30, true),
  ('Viva Verde', 30, true),
  ('Love Sudamericana', 30, true),
  ('Dermapet', 30, true),
  ('Ownat', 30, true),
  ('Green Line Repel', 30, true),
  ('Vet Expert', 30, true),
  ('Naturalistic', 30, true),
  ('Biofresh', 30, true),
  ('Sanicat', 30, true),
  ('Kissito', 30, true),
  ('Biomont - Imperia', 30, true),
  ('Imagine Animal Health', 30, true),
  ('Bimeda', 30, true),
  ('Agrovet-Petmedica', 30, true),
  ('Sprinkle & Sweep', 30, true),
  ('Holliday', 30, true),
  ('Origo', 30, true),
  ('Cutania', 30, true),
  ('Formula Natural', 30, true),
  ('Nutri Bites', 30, true),
  ('Pet Delicia', 30, true),
  ('Orijen', 30, true),
  ('Pets Protector 90', 30, true),
  ('Qhali Pets', 30, true),
  ('Claws & Paws', 30, true),
  ('Animal Spirit', 30, true),
  ('Bio Buddy', 30, true),
  ('Only Natural Pet', 30, true),
  ('Araton', 30, true),
  ('Veterline-Ephecto', 30, true),
  ('Acalma', 30, true),
  ('Sergeants', 30, true),
  ('Docg', 30, true),
  ('Adaptil', 30, true),
  ('Feliway', 30, true),
  ('Yoos', 30, true),
  ('Esencias Florales', 30, true),
  ('Veterinary Formula', 30, true),
  ('Synergy Labs', 30, true),
  ('Soft Care', 30, true),
  ('Hydra', 30, true),
  ('Shed-X', 30, true),
  ('Organnact', 30, true),
  ('Acana', 30, true),
  ('Nerf Dog', 30, true),
  ('Nuevo', 30, true),
  ('Abelia', 30, true),
  ('Aprax', 30, true),
  ('Nylabone', 30, true),
  ('Protect', 30, true),
  ('Pure Life', 30, true),
  ('Dr Edwards', 30, true),
  ('Felifat', 30, true),
  ('N&D', 30, true),
  ('Matisse', 30, true)
ON CONFLICT (nombre) DO NOTHING;

-- 5. Enable RLS
ALTER TABLE public.marcas_control ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies
-- Everyone authenticated can read
CREATE POLICY "Authenticated users can read marcas_control" ON public.marcas_control
FOR SELECT USING (auth.role() = 'authenticated');

-- Only admin can write
CREATE POLICY "Only admin can modify marcas_control" ON public.marcas_control
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.usuarios WHERE id = auth.uid() AND rol = 'admin'
  )
);
